tags = ["Web", "Simplicity", "Meta", "Book"]

[[projects]]
name = "bridge"
title = "Bridge.gg"
order = 0

[[articles]]
name = "mindstorms"
description = "A book review"
title = "Mindstorms: Children, Computers and Powerful Ideas"
date = 2020-10-12
tags = ["Book"]

[[articles]]
name = "static_web_content"
description = "kaikki on pilalla"
title = "Static web content"
date = 2020-10-02
tags = ["Web", "Simplicity", "Meta"]
