[[quotes]]
text = "To attain knowledge, add things every day. To attain wisdom, remove things every day."
author = "Lao Tzu"

[[quotes]]
text = "To continue we require more than intelligence. We require wisdom."
author = "David Attenborough"

[[quotes]]
text = "Imaginary mountains build themselves from our efforts to climb them."
author = "Bennett Foddy"

[[quotes]]
text = "Simplicity is the ultimate sophistication."
author = "Leonardo da Vinci"