[[quotes]]
text = "To attain knowledge, add things every day. To attain wisdom, remove things every day."
author = "Lao Tzu"

[[quotes]]
text = "To continue, we require more than intelligence. We require wisdom."
author = "David Attenborough"

[[quotes]]
text = "Imaginary mountains build themselves from our efforts to climb them."
author = "Bennett Foddy"

[[quotes]]
text = "Simplicity is the ultimate sophistication."
author = "Leonardo da Vinci"

[[quotes]]
text = "Everything should be made as simple as possible, but not simpler."
author = "Albert Einstein via Roger Session"

[[quotes]]
text = "A cynic knows the price of everything, and the value of nothing."
author = "Oscar Wilde"

[[quotes]]
text = "I want to learn more and more to see as beautiful what is necessary in things; then I shall be one of those who makes things beautiful. Amor fati: let that be my love henceforth!"
author = "Friedrich Nietzsche"
